name: CI

on:
  push:
    branches:
      - main  # or replace with the name of your default branch, e.g., 'master'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # or another version if preferred

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test  # Make sure you have a test script in your package.json, or remove this step if you don't have tests
